env:
  browser: true
  commonjs: true
  es2020: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules:
  no-useless-catch: 'off'
  no-undef: 'off'
  indent:
    - error
    - tab
  linebreak-style: 'off'
  quotes:
    - error
    - single
  semi:
    - error
    - always